apiVersion: "nuclio.io/v1beta1"
kind: "NuclioFunction"
spec:
  description: Showcases unstructured logging and a structured response.
  runtime: "golang"
  minReplicas: 1
  maxReplicas: 1
  handler: main:Handler